// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIoDOBuXQ8SzTnj5uK4Cp8YEYO9s2gYGw',
    appId: '1:1007290131953:web:1cabc07fa0b4ac581a1050',
    messagingSenderId: '1007290131953',
    projectId: 'scheduling-app-f97d9',
    authDomain: 'scheduling-app-f97d9.firebaseapp.com',
    storageBucket: 'scheduling-app-f97d9.firebasestorage.app',
    measurementId: 'G-8V6H8JPGHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSQo8MtFgaiqtkyyJEXaGN-xMLRmBEOQQ',
    appId: '1:1007290131953:android:655b6e2970d1888e1a1050',
    messagingSenderId: '1007290131953',
    projectId: 'scheduling-app-f97d9',
    storageBucket: 'scheduling-app-f97d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5ktnWor1ia9jJ53uLpCka5xpY3upMMg',
    appId: '1:1007290131953:ios:07badc10ad833cf61a1050',
    messagingSenderId: '1007290131953',
    projectId: 'scheduling-app-f97d9',
    storageBucket: 'scheduling-app-f97d9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR5ktnWor1ia9jJ53uLpCka5xpY3upMMg',
    appId: '1:1007290131953:ios:07badc10ad833cf61a1050',
    messagingSenderId: '1007290131953',
    projectId: 'scheduling-app-f97d9',
    storageBucket: 'scheduling-app-f97d9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIoDOBuXQ8SzTnj5uK4Cp8YEYO9s2gYGw',
    appId: '1:1007290131953:web:c0e032d37ef32ad81a1050',
    messagingSenderId: '1007290131953',
    projectId: 'scheduling-app-f97d9',
    authDomain: 'scheduling-app-f97d9.firebaseapp.com',
    storageBucket: 'scheduling-app-f97d9.firebasestorage.app',
    measurementId: 'G-2GBF96EFFY',
  );
}